version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of PHP version: 8, 8.1, 8.0, 7, 7.4
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "8-bullseye"
        # Optional Node.js version
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached
      - mongodb-data:/data/db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongodb
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongodb:
    image: mongo:6.0
    command: --quiet
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      #environment:
      # Optional, turn on auth
      #- MONGO_INITDB_ROOT_USERNAME=root
      #- MONGO_INITDB_ROOT_PASSWORD=password123
      # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:
